-- AR Studio Recording — Supabase schema
-- Jalankan seluruh file ini di Supabase SQL Editor.

create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);

create table if not exists public.services (
  id text primary key,
  title text not null,
  description text not null default '',
  icon text not null default 'wave',
  sort_order integer not null default 999,
  active boolean not null default true
);

create table if not exists public.audio_portfolio (
  id text primary key,
  title text not null,
  artist text not null default '',
  cover_url text not null default '',
  audio_url text not null default '',
  duration text not null default '',
  sort_order integer not null default 999,
  active boolean not null default true
);

create table if not exists public.video_portfolio (
  id text primary key,
  title text not null,
  subtitle text not null default '',
  youtube_id text not null default '',
  thumbnail_url text not null default '',
  sort_order integer not null default 999,
  active boolean not null default true
);

create table if not exists public.price_list (
  id text primary key,
  service text not null,
  price text not null default '',
  unit text not null default '',
  features text not null default '',
  sort_order integer not null default 999,
  active boolean not null default true,
  description text not null default '',
  details text not null default '',
  notes text not null default ''
);

create table if not exists public.gallery (
  id text primary key,
  title text not null,
  image_url text not null default '',
  sort_order integer not null default 999,
  active boolean not null default true,
  category text not null default 'Studio'
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  booking_id text not null unique,
  name text not null check (char_length(name) between 1 and 80),
  whatsapp text not null check (char_length(whatsapp) between 5 and 30),
  service text not null check (char_length(service) between 1 and 100),
  booking_date date not null,
  booking_time text not null check (char_length(booking_time) between 1 and 30),
  notes text not null default '' check (char_length(notes) <= 1000),
  source text not null default '',
  status text not null default 'Baru'
);

-- RLS
alter table public.settings enable row level security;
alter table public.services enable row level security;
alter table public.audio_portfolio enable row level security;
alter table public.video_portfolio enable row level security;
alter table public.price_list enable row level security;
alter table public.gallery enable row level security;
alter table public.bookings enable row level security;

-- Least privilege grants
revoke all on public.settings, public.services, public.audio_portfolio, public.video_portfolio, public.price_list, public.gallery, public.bookings from anon;
grant select on public.settings, public.services, public.audio_portfolio, public.video_portfolio, public.price_list, public.gallery to anon;
grant insert on public.bookings to anon;

grant select on public.settings, public.services, public.audio_portfolio, public.video_portfolio, public.price_list, public.gallery to authenticated;
grant insert on public.bookings to authenticated;
grant usage, select on sequence public.bookings_id_seq to anon, authenticated;

-- Public website may read settings and only active content.
drop policy if exists "public read settings" on public.settings;
create policy "public read settings" on public.settings for select to anon, authenticated using (true);

drop policy if exists "public read active services" on public.services;
create policy "public read active services" on public.services for select to anon, authenticated using (active = true);

drop policy if exists "public read active audio" on public.audio_portfolio;
create policy "public read active audio" on public.audio_portfolio for select to anon, authenticated using (active = true);

drop policy if exists "public read active video" on public.video_portfolio;
create policy "public read active video" on public.video_portfolio for select to anon, authenticated using (active = true);

drop policy if exists "public read active prices" on public.price_list;
create policy "public read active prices" on public.price_list for select to anon, authenticated using (active = true);

drop policy if exists "public read active gallery" on public.gallery;
create policy "public read active gallery" on public.gallery for select to anon, authenticated using (active = true);

-- Visitor may create a booking, but cannot read/update/delete bookings.
drop policy if exists "public create booking" on public.bookings;
create policy "public create booking" on public.bookings for insert to anon with check (
  char_length(name) between 1 and 80 and
  char_length(whatsapp) between 5 and 30 and
  char_length(service) between 1 and 100 and
  char_length(notes) <= 1000
);

-- Content administration is intentionally done from the Supabase Dashboard.
-- No browser user receives update/delete rights to website tables.

-- Seed price list from the current project
insert into public.price_list (id,service,price,unit,features,description,details,notes,active,sort_order) values
('overdub-recording','Overdub Recording','Rp150.000','/ jam','Rp360.000 / 1/2 shift (3 jam)|Rp600.000 / shift (5 jam)','Layanan overdub recording untuk vocal maupun instrumen dengan pilihan durasi per jam, setengah shift, atau full shift.','Rp150.000 / jam|Rp360.000 / 1/2 shift (3 jam)|Rp600.000 / shift (5 jam)','Booking melalui WhatsApp: 0857-2209-6345',true,1),
('aransemen-midi-instrumen','Aransemen MIDI / Instrumen','Rp850.000','mulai','No Mixing|Mixing & Mastering Basic|Take Vocal / Edit Vocal','Paket aransemen MIDI/instrumen dari produksi dasar sampai paket lengkap dengan take dan editing vocal.','Rp850.000 — Aransemen, tanpa mixing|Rp1.200.000 — Aransemen + Mixing & Mastering Basic|Rp1.600.000 — Aransemen + Take Vocal/Edit Vocal + Mixing & Mastering Basic','Detail kebutuhan aransemen dan referensi musik dapat dibahas saat booking.',true,2),
('jingle','Jingle','Rp3.500.000','mulai','Aransemen musik|Pembuatan nada & lirik','Produksi jingle untuk brand, sekolah, bisnis, campaign, atau kebutuhan promosi.','Rp3.500.000 — Aransemen musik|Rp5.500.000 — Membuat nada & lirik','Brief, durasi, penggunaan komersial, dan referensi gaya musik dibahas sebelum produksi.',true,3),
('paket-video-cover','Paket Video Cover','Rp800.000','/ paket','Take vocal|3 angle video indoor|Editing video|Mixing & mastering','Paket produksi video cover indoor dengan proses take vocal, multi-angle video, editing, mixing, dan mastering.','Musik / backing track disiapkan sendiri|Take vocal setengah shift (3 jam)|3 angle video indoor|Editing video|Mixing + mastering','Musik disiapkan sendiri oleh client.',true,4),
('mixing','Mixing','Rp350.000','mulai','Vocal editing|Vocal tuning basic|Timing correction|EQ|Compression|Reverb & Delay|Stereo imaging|Automation|Balancing|Mix bus processing|WAV + MP3|2x revisi','Mixing multitrack lengkap dengan editing dasar, balancing, processing, automation, dan final mix.','Rp350.000 — 1–10 track|Rp500.000 — 11–20 track|Rp700.000 — 21–50 track|Rp1.000.000 — lebih dari 50 track|Vocal editing|Vocal tuning basic|Timing correction|EQ|Compression|Reverb & Delay|Stereo imaging|Automation|Vocal & instrumental balancing|Mix bus processing|Final mix WAV + MP3|2x revisi','Harga mengikuti jumlah track pada project.',true,5),
('mastering','Mastering','Rp300.000–500.000','/ lagu','EQ tonal balancing|Compression|Limiting|Stereo enhancement|Loudness optimization|Dynamic control|Streaming optimization|WAV Master|MP3 Master','Finalisasi audio agar tonal balance, dinamika, loudness, dan format akhir siap untuk distribusi.','EQ tonal balancing|Compression|Limiting|Stereo enhancement|Loudness optimization|Dynamic control|Streaming optimization|WAV Master|MP3 Master','Harga Rp300.000–Rp500.000 per lagu, menyesuaikan kebutuhan materi.',true,6)
on conflict (id) do update set service=excluded.service,price=excluded.price,unit=excluded.unit,features=excluded.features,description=excluded.description,details=excluded.details,notes=excluded.notes,active=excluded.active,sort_order=excluded.sort_order;

-- Starter services; edit freely in Table Editor.
insert into public.services (id,title,description,icon,sort_order,active) values
('recording','Recording','Recording vocal dan instrumen dengan workflow studio profesional.','mic',1,true),
('mixing','Mixing','Balancing, editing, processing, dan automation untuk mix yang solid.','sliders',2,true),
('mastering','Mastering','Finalisasi loudness, tonal balance, dan delivery siap rilis.','wave',3,true),
('arrangement','Arrangement','Aransemen musik dan produksi MIDI/instrumen.','pen',4,true),
('video','Video Cover','Produksi video cover indoor lengkap dengan editing.','video',5,true)
on conflict (id) do nothing;

-- ===== Portfolio/Profile upgrade =====
alter table public.audio_portfolio add column if not exists role text not null default '';
alter table public.audio_portfolio add column if not exists year text not null default '';
alter table public.audio_portfolio add column if not exists genre text not null default '';

create table if not exists public.case_studies (
  id text primary key,
  title text not null,
  project text not null default '',
  genre text not null default '',
  work text not null default '',
  before_url text not null default '',
  after_url text not null default '',
  description text not null default '',
  sort_order integer not null default 999,
  active boolean not null default true
);

create table if not exists public.testimonials (
  id text primary key,
  client text not null,
  project text not null default '',
  quote text not null,
  photo_url text not null default '',
  sort_order integer not null default 999,
  active boolean not null default true
);

alter table public.case_studies enable row level security;
alter table public.testimonials enable row level security;
revoke all on public.case_studies, public.testimonials from anon;
grant select on public.case_studies, public.testimonials to anon, authenticated;
drop policy if exists "public read active case studies" on public.case_studies;
create policy "public read active case studies" on public.case_studies for select to anon, authenticated using (active = true);
drop policy if exists "public read active testimonials" on public.testimonials;
create policy "public read active testimonials" on public.testimonials for select to anon, authenticated using (active = true);

insert into public.settings(key,value) values
('studioName','AR Studio Recording'),
('eyebrow','AR STUDIO RECORDING'),
('heroTitle','RECORDING. MIXING. MUSIC PRODUCTION.'),
('heroSubtitle','Helping artists turn ideas into finished records.'),
('engineerName','Afif Ramdhan'),
('engineerRole','Recording & Mixing Engineer / Music Producer'),
('engineerBio','Saya membantu musisi mengubah ide dan rekaman mentah menjadi produksi musik yang siap dirilis — dari recording, editing, mixing, mastering, hingga arrangement.'),
('footerText','AR Studio Recording · Recording · Mixing · Music Production')
on conflict(key) do update set value=excluded.value;
